### ISSUE TITLE
Would be nice if this project has a more descriptive README.md file

### ISSUE THREAD

**Issue by davidconoh** [oscommunityafrica/oscommunityafrica.github.io#17]
@samswag Would be nice if this repository displayed a more descriptive **README.md** file that outlines all the necessary information about this project, instead of the **README.txt** file for the Forty by HTML5 Up template used.

**Comment by samswag** [comment]
Sure, you can look into the codebase and create something, or do you need any help?

**Comment by davidconoh** [comment]
I'll start working on something immediately.
Thanks.

**Comment by BolajiAyodeji** [comment]
Fixed!
