### ISSUE TITLE
Is it safe/recommended to make PRs directly to the master branch?

### ISSUE THREAD

**Issue by davidconoh** [oscommunityafrica/oscommunityafrica.github.io#18]
@samswag @Kolokodess I suggest we setup some other branches, maybe a `devel` branch for PRs from external contributors so they can be very well accessed for conflicts before pushing to master branch for security reasons and to encourage best practices. I don't think external contributors like me making direct PRs to the `master` branch is a good idea as I have a patch to submit.

**Comment by samswag** [comment]
Yes, I totally agree.

**Comment by davidconoh** [comment]
Cool! If you'd create a `devel` branch where we can make pull requests, that would be very nice.
Thanks.

**Comment by kodekage** [comment]
@samswag i'm still on it, just some webpack issues holding me back..

**Comment by detygon** [comment]
Ah oquay! I just forked the repo. I noticed that the webpack config is empty so how do you manage the build ?
