### ISSUE TITLE
Size of the Footer 

### ISSUE THREAD

**Issue by perriefidelis** [oscommunityafrica/oscommunityafrica.github.io#24]
Reduce the height of the footer: It's currently at 885x206.59, reduce it to 885x180
<img width="1440" alt="OSCA footer" src="https://user-images.githubusercontent.com/30669761/45961850-6bca4900-c017-11e8-9ebe-ac1fe37074c1.png">

**Comment by prondubuisi** [comment]
Has this issue been fixed @perriefidelis, if it hasn't we might add first timer label
