### ISSUE TITLE
Add menu design change

### ISSUE THREAD

**Issue by perriefidelis** [oscommunityafrica/oscommunityafrica.github.io#34]
**feature request to change the menu page**

I added another action button(host an event)

![menu](https://user-images.githubusercontent.com/30669761/46035007-ebc8df80-c0f9-11e8-9359-c375c11ffc36.png)

**Comment by perriefidelis** [comment]
here is the link: https://www.figma.com/file/PP3hT8RdmlifUZKta6huVtW0/OSCA?node-id=135%3A0

**Comment by BolajiAyodeji** [comment]
@samswag All setup, it worked!!
I just subscribed with my email

**Comment by BolajiAyodeji** [comment]
One last tweak, you should add OSCA logo at the top of the form and align center
like this https://upnepa.us19.list-manage.com/subscribe/post?u=d9cfbfd60cd78101f81078bd1&id=908fcec3d4

**Comment by BolajiAyodeji** [comment]
Also, why is the name `Open Source Community Africa - Newbies` ? @samswag 
![image](https://user-images.githubusercontent.com/30334776/51444633-5a115d80-1cfa-11e9-9a09-5aa465f13223.png)
