### ISSUE TITLE
Nav bar (Logo) conflicting with the image

### ISSUE THREAD

**Issue by samswag** [oscommunityafrica/oscommunityafrica.github.io#42]
After I merged the pull request. The community page is having an issue the navigation. I am guessing, the problem is from the large image(map).

@Pheonix73 do you want to check it out?

**Comment by perriefidelis** [comment]
The logo isn’t placed properly either. 
I’m seeing a lot of alignment issues.
The about us area of the page looks totally different from other parts of the site with that same position

**Comment by samswag** [comment]
> The logo isn’t placed properly either.
> I’m seeing a lot of alignment issues.
> The about us area of the page looks totally different from other parts of the site with that same position

I will advise you create a new issue for it... Again the About US is not on the website. Please add a screenshot to make developers understand.

**Comment by perriefidelis** [comment]
> > The logo isn’t placed properly either.
> > I’m seeing a lot of alignment issues.
> > The about us area of the page looks totally different from other parts of the site with that same position
> 
> I will advise you create a new issue for it... Again the About US is not on the website. Please add a screenshot to make developers understand.

Done!
