### ISSUE TITLE
Poor Alignment 

### ISSUE THREAD

**Issue by perriefidelis** [oscommunityafrica/oscommunityafrica.github.io#45]
**The alignment on the community page should be improved** 

<img width="1440" alt="screen shot 2018-09-26 at 6 13 54 pm" src="https://user-images.githubusercontent.com/30669761/46097881-f0a19800-c1ba-11e8-8d9a-fd6d8b59f9d6.png">

1. Above, the area where the "about us" section is different from other similar parts of the site as compared to the home page as shown below;
2. The same font and font properties should be used 

<img width="1439" alt="screen shot 2018-09-26 at 6 13 14 pm" src="https://user-images.githubusercontent.com/30669761/46097848-d962aa80-c1ba-11e8-86ed-e71d0c2b22e5.png">

**Call to action buttons**
<img width="1432" alt="screen shot 2018-09-26 at 6 29 22 pm" src="https://user-images.githubusercontent.com/30669761/46097941-1a5abf00-c1bb-11e8-93a3-4b4f4cc425bc.png">

The call to action buttons are not properly aligned;
1. the buttons are not in the middle of the page as shown above.
2. the elements in the button aren't aligned in the center properly. see below;
* <img width="248" alt="screen shot 2018-09-26 at 6 29 28 pm" src="https://user-images.githubusercontent.com/30669761/46098043-568e1f80-c1bb-11e8-965e-bce8873174c1.png">

<img width="257" alt="screen shot 2018-09-26 at 6 29 32 pm" src="https://user-images.githubusercontent.com/30669761/46098057-60178780-c1bb-11e8-9d1e-e16feead80c2.png">

**Comment by Pheonix73** [comment]
Thats really true

**Comment by Pheonix73** [comment]
Fixed

**Comment by perriefidelis** [comment]
@Pheonix73 haven't seen any change

**Comment by samswag** [comment]
<img width="1132" alt="screenshot 2018-09-27 at 12 44 14 pm" src="https://user-images.githubusercontent.com/6048601/46143825-137f8b00-c253-11e8-8f99-16f90fc82608.png">

The footer was fixed

**Comment by perriefidelis** [comment]
I've reloaded several times on chrome .. not seen changes, maybe it's from my browser

**Comment by samswag** [comment]
Clear your cache.

**Comment by perriefidelis** [comment]
okay seen.
