### ISSUE TITLE
Community Page not responsive for mobile. 

### ISSUE THREAD

**Issue by samswag** [oscommunityafrica/oscommunityafrica.github.io#50]
I noticed that the site is not responsive on mobile devices.

**Comment by Youngestdev** [comment]
It's quite responsive over here . What responsive features do you notice are missing ?

**Comment by samswag** [comment]
![screenshot_20180927-130812_chrome](https://user-images.githubusercontent.com/6048601/46144985-88a08f80-c256-11e8-9f43-bad4e6d476f8.jpg)
![screenshot_20180927-130806_chrome](https://user-images.githubusercontent.com/6048601/46144998-8f2f0700-c256-11e8-9a0d-59737c292d3a.jpg)

Try scrolling or sliding to the left... See image

**Comment by Pheonix73** [comment]
The Page is not yet Responsive, not added any Media Queries Yet.

**Comment by OPARA-PROSPER** [comment]
@Pheonix73 Looks like media queries has been added, Its responsive on my end

**Comment by NedyUdombat** [comment]
This issue has been fixed 
the community page is now responsive for all screen sizes
