### ISSUE TITLE
Mobile view of the community page

### ISSUE THREAD

**Issue by perriefidelis** [oscommunityafrica/oscommunityafrica.github.io#52]
![mobile view of the community page](https://user-images.githubusercontent.com/30669761/46155764-fa390780-c26f-11e8-9384-01e5b48274a9.png)

**Comment by OPARA-PROSPER** [comment]
Looks Responsive...

**Comment by BolajiAyodeji** [comment]
Really awesome!
I love it

**Comment by NedyUdombat** [comment]
That is the design and not the implementations yeah? @perriefidelis
