### ISSUE TITLE
Difference in font

### ISSUE THREAD

**Issue by perriefidelis** [oscommunityafrica/oscommunityafrica.github.io#64]
**Same font type/style/sizes should be used throughout the site for consistency**
The font type and size used in the home page is different from that in the community page

<img width="1429" alt="screen shot 2018-09-29 at 12 09 43 pm" src="https://user-images.githubusercontent.com/30669761/46245182-a0f0e580-c3e1-11e8-8507-400b4a521025.png">

The picture above shows the font type and style of the site's font to be used, below shows the current one on the community page; 

<img width="1440" alt="screen shot 2018-09-29 at 12 09 25 pm" src="https://user-images.githubusercontent.com/30669761/46245174-8f0f4280-c3e1-11e8-90fd-3d1e2f980622.png">

**Comment by BolajiAyodeji** [comment]
Help coming soon!

**Comment by NedyUdombat** [comment]
Has this been fixed? @perriefidelis  and @BolajiAyodeji
