### ISSUE TITLE
Would be nice to have a loader on the site.

### ISSUE THREAD

**Issue by samswag** [oscommunityafrica/oscommunityafrica.github.io#8]

**Comment by tosinibrahim96** [comment]
@samswag i dont know if this issue is still open. Am still early in my learning journey though but i would love to help. I actually attended the OSCA meetup at ken-saro-wiwa hub and i'm following your instructions. #startfromtheIssues

**Comment by samswag** [comment]
<img width="1280" alt="screenshot 2018-11-11 at 4 20 13 pm" src="https://user-images.githubusercontent.com/6048601/48314725-b440c480-e5cd-11e8-9770-e278eafc2696.png">

<img width="1280" alt="screenshot 2018-11-11 at 4 20 06 pm" src="https://user-images.githubusercontent.com/6048601/48314743-e2be9f80-e5cd-11e8-8b48-fc30829558da.png">

**Comment by samswag** [comment]
<img width="1280" alt="screenshot 2018-11-11 at 4 22 56 pm" src="https://user-images.githubusercontent.com/6048601/48314751-18638880-e5ce-11e8-80ad-f869769a5ac9.png">
<img width="1280" alt="screenshot 2018-11-11 at 4 22 59 pm" src="https://user-images.githubusercontent.com/6048601/48314752-21ecf080-e5ce-11e8-8547-f2cca68bb81c.png">

Just like I said before the font you are using is applealing the eyes. Could you make a fix for now without changing any fonts?
